name: "default"
language: "fr"
title: "admin"
akas:
  - "master"
  - "admin"
security_level: 0
restAPI_password: "fakepass"
pmdl: "trigger/snowboy/resources/aila.pmdl"
tts:
  name: 'pico2wave'
  parameters:
    language: "fr-FR"
    cache: True
neurons_parameters:
  neuron_name:
    params1: "foo"
    params2: "bar"
